name: despesas

services:
    database:
      image: postgres:11.13-alpine
      container_name: despesas-database
      environment:
        POSTGRES_USER: despesas
        POSTGRES_PASSWORD: despesas_db
        POSTGRES_DB: despesas
      ports:
        - "5432:5432"
      volumes:
        - /despesas-postgres:/var/lib/postgresql/data

    app:
      image: leokaos/despesas:0.1
      container_name: despesas-app
      ports:
        - "8080:8080"